Add GPTQ class
HabanaAI/vllm-hpu-extension pull request #28
Opened 2024-11-08 22:43 UTC by maktukmak

Based on https://github.com/HabanaAI/vllm-fork/pull/481, I added gptq hpu class for enabling GPTQ quantized models.

2024-11-13 08:03 UTC, michalkuligowski requested changes

2024-11-19 17:22 UTC, maktukmak commented on vllm_hpu_extension/gptq_hpu.py
> +import enum
It uses reimplementations of some functions from that file. What do you suggest as the header?

2024-12-11 14:45 UTC, michalkuligowski commented
Awaiting legal input on licensing

2025-01-09 22:44 UTC, maktukmak commented on vllm_hpu_extension/gptq_hpu.py
> +        assert torch.equal(layer.g_idx, g_idx_trivial), "Non-trivial tensor g_idx is not supported"
It is expected due to the HPU kernel not supporting the desc_asc=true feature.

2025-01-09 22:46 UTC, maktukmak commented on vllm_hpu_extension/gptq_hpu.py
> +from enum import Enum
Removed

2025-01-09 22:46 UTC, maktukmak commented on vllm_hpu_extension/gptq_hpu.py
> +from vllm import _custom_ops as ops
Removed

2025-01-16 08:13 UTC, merged